const assert = require('assert')
const fs = require('fs')
const path = require('path')

const profileScript = fs.readFileSync(path.join(__dirname, '..', 'pages', 'profile', 'profile.js'), 'utf8')
const profileMarkup = fs.readFileSync(path.join(__dirname, '..', 'pages', 'profile', 'profile.wxml'), 'utf8')

assert(profileScript.includes("require('../../services/authService')"), 'profile page should use the auth service boundary')
assert(profileScript.includes('getStoredAuth'), 'profile page should read stored auth on show')
assert(profileScript.includes('getWechatLoginCode'), 'profile page should bind wx.login code with phone login when available')
assert(profileScript.includes('loginWithWechatPhone'), 'profile page should submit phone authorization code to API')
assert(profileScript.includes('updateProfile'), 'profile page should save wechat profile to API')
assert(profileScript.includes('uploadAvatar'), 'profile page should upload selected wechat avatar to API')
assert(profileScript.includes('handlePhoneLogin'), 'profile page should handle native getPhoneNumber result')
assert(profileScript.includes('openProfileEditor'), 'profile page should open wechat profile editor')
assert(profileScript.includes('saveWechatProfile'), 'profile page should save wechat profile editor changes')
assert(profileScript.includes('clearAuth'), 'profile page should support logout')
assert(profileScript.includes('handleLogout'), 'profile page should expose a logout handler')
assert(!profileScript.includes('loginWithPassword'), 'profile page should not use password login')
assert(!profileScript.includes('loginWithWechatCode'), 'profile page should not use plain wx.login as the primary login')
assert(!profileScript.includes('handleWechatLogin'), 'profile page should not use a custom tap-only wechat login')
assert(!profileScript.includes('loginMobile'), 'profile page should not keep mobile login state')
assert(!profileScript.includes('loginPassword'), 'profile page should not keep password login state')
assert(!profileScript.includes('showWechatLoginSheet'), 'profile page should not keep a custom login sheet')
assert(!profileScript.includes('wechatNickname'), 'profile page should not require nickname before phone login')
assert(!profileScript.includes('wechatAvatarUrl'), 'profile page should not require avatar before phone login')

assert(profileMarkup.includes('wx:if="{{!isLoggedIn}}"'), 'profile page should show login panel when logged out')
assert(profileMarkup.includes('open-type="getPhoneNumber"'), 'profile login button should use native phone number authorization')
assert(profileMarkup.includes('bindgetphonenumber="handlePhoneLogin"'), 'profile login button should receive native phone authorization result')
assert(profileMarkup.includes('wx:if="{{isLoggedIn}}"'), 'profile page should show user profile when logged in')
assert(profileMarkup.includes('bindtap="handleLogout"'), 'profile page should allow logout')
assert(profileMarkup.includes('bindtap="openProfileEditor"'), 'profile page should expose wechat profile editing')
assert(profileMarkup.includes('open-type="chooseAvatar"'), 'profile editor should use native avatar choosing')
assert(profileMarkup.includes('type="nickname"'), 'profile editor should use native nickname input')
assert(profileMarkup.includes('bindtap="saveWechatProfile"'), 'profile editor should save profile changes')
assert(profileMarkup.includes('小程序与网页端数据互通'), 'profile page should explain mini-program and web data sharing')
assert(profileMarkup.includes('profile-mobile'), 'profile page should render mobile on its own line')
assert(profileMarkup.includes('profile-sync-copy'), 'profile page should render data sharing copy on its own line')
assert(!profileMarkup.includes('检测记录将同步到账号'), 'profile page should not use the old sync copy')
assert(!profileMarkup.includes("}} · 小程序与网页端数据互通"), 'profile page should not combine mobile and sync copy in one line')
assert(!profileMarkup.includes('bindinput="onMobileInput"'), 'profile page should not collect mobile input')
assert(!profileMarkup.includes('password="{{true}}"'), 'profile page should not collect password input')
assert(!profileMarkup.includes('管理员'), 'mini-program profile should not show admin wording')
assert(!profileMarkup.includes('wechat-login-mask'), 'profile page should not render a custom login mask')
