const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..')

function read(file) {
  return fs.readFileSync(path.join(root, file), 'utf8')
}

const homeTemplate = read('pages/index/index.wxml')
const detectTemplate = read('pages/detect/detect.wxml')
const detectScript = read('pages/detect/detect.js')
const profileTemplate = read('pages/profile/profile.wxml')
const profileScript = read('pages/profile/profile.js')
const profileReportsTemplate = read('pages/profile-reports/profile-reports.wxml')
const profileReportsScript = read('pages/profile-reports/profile-reports.js')
const detailTemplate = read('pages/report-detail/report-detail.wxml')
const detailScript = read('pages/report-detail/report-detail.js')
const appConfig = require('../app.json')

assert(!homeTemplate.includes('最近检测报告'), 'home should not show the report history module')

assert(detectScript.includes('saveDetectionReport'), 'detect page should save a report after successful detection')
assert(detectScript.includes('getRecentReports'), 'detect page should load local report history')
assert(detectScript.includes('DETECT_REPORT_PREVIEW_LIMIT'), 'detect page should define a compact report preview limit')
assert(detectScript.includes('getRecentReports(null, DETECT_REPORT_PREVIEW_LIMIT)'), 'detect page should load only the latest three report previews')
assert(detectScript.includes('openReportDetail'), 'detect page should navigate to saved report details')
assert(detectScript.includes('openReportList'), 'detect page should navigate to the full report list')
assert(detectTemplate.includes('最近检测报告'), 'detect page should show recent report history')
assert(detectTemplate.includes('recentReports'), 'detect page should render recent local reports')
assert(detectTemplate.includes('bindtap="openReportDetail"'), 'detect report history rows should be tappable')
assert(detectTemplate.includes('data-id="{{item.id}}"'), 'detect report history rows should pass the report ID')
assert(detectTemplate.includes('查看全部检测报告'), 'detect page should offer a full report list action below the three latest reports')

assert(profileScript.includes('getRecentReports'), 'profile page should load local report history')
assert(profileScript.includes('buildProfileMenus'), 'profile page should build function menu status from local reports')
assert(!profileScript.includes('TikTok Shop关键词检测'), 'profile page should not keep mock report records')
assert(!profileTemplate.includes('<text class="section-title">最近检测报告</text>'), 'profile page should not render report history as a separate section')

assert(appConfig.pages.includes('pages/profile-reports/profile-reports'), 'app should register the report list page')
assert(profileReportsScript.includes('getRecentReports'), 'report list page should load all local reports')
assert(profileReportsScript.includes('openReportDetail'), 'report list page should navigate to saved report details')
assert(profileReportsTemplate.includes('我的检测报告'), 'report list page should title the full report list')
assert(profileReportsTemplate.includes('records.length'), 'report list page should branch on local report records')
assert(profileReportsTemplate.includes('bindtap="openReportDetail"'), 'report list rows should be tappable')
assert(profileReportsTemplate.includes('完成检测后会在这里集中展示'), 'report list page should show an empty state before records exist')

assert(appConfig.pages.includes('pages/report-detail/report-detail'), 'app should register the report detail page')
assert(detailScript.includes('getReportById'), 'report detail page should load saved records by ID')
assert(detailScript.includes('downloadFile'), 'report detail page should download generated PDF reports')
assert(detailScript.includes('openDocument'), 'report detail page should open generated PDF reports')
assert(detailScript.includes("fileType: 'pdf'"), 'report detail page should mark opened documents as PDFs')
assert(detailTemplate.includes('report.pdfReportFileID'), 'report detail page should show a PDF action when a PDF exists')
assert(detailTemplate.includes('report.trademarkCandidates'), 'report detail page should render saved USPTO candidates')
