const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..')

function read(file) {
  return fs.readFileSync(path.join(root, file), 'utf8')
}

const toolsTemplate = read('pages/tools/tools.wxml')
const toolsScript = read('pages/tools/tools.js')
const toolsStyles = read('pages/tools/tools.wxss')
const mockData = require('../data/mock')
const appConfig = require('../app.json')

assert(!toolsTemplate.includes('知识产权服务'), 'tools page should not show an IP service module')
assert(!toolsTemplate.includes('services'), 'tools page should not render the removed service list')
assert(!toolsTemplate.includes('跟卖'), 'tools page should not mention follow-sell monitoring after removal')
assert(!toolsScript.includes('services:'), 'tools page data should not keep removed service pills')
assert(!toolsStyles.includes('.service-card'), 'tools page should not keep removed service card styles')
assert(!toolsStyles.includes('.service-pill'), 'tools page should not keep removed service pill styles')

assert(!toolsTemplate.includes('工具入口'), 'tools page should remove the tool entry section title')
assert(!toolsTemplate.includes('tools-grid'), 'tools page should remove the tool entry grid')
assert(!toolsTemplate.includes('tool-card'), 'tools page should remove tool entry cards')
assert(!toolsTemplate.includes('tool-icon'), 'tools page should remove tool entry icons')
assert(!toolsScript.includes('toolCards'), 'tools page script should not import tool entry data')
assert(!toolsScript.includes('tools:'), 'tools page data should not expose tool entry cards')
assert(!toolsScript.includes('openTool'), 'tools page should remove the removed entry tap handler')
assert(!toolsStyles.includes('.tools-grid'), 'tools page should remove tool grid styles')
assert(!toolsStyles.includes('.tool-card'), 'tools page should remove tool card styles')
assert(!toolsStyles.includes('.tool-icon'), 'tools page should remove tool icon styles')
assert(!Object.prototype.hasOwnProperty.call(mockData, 'toolCards'), 'shared mock data should not export removed tool entry cards')

assert(toolsScript.includes('openTemplateGenerator'), 'tools page should navigate to the template generator page')
assert(toolsScript.includes('/pages/appeal-template/appeal-template?platform='), 'tools page should pass selected platform to generator page')
assert(toolsScript.includes('wx.navigateTo'), 'tools page should use page navigation for template generation')
assert(!toolsScript.includes("require('../../services/appealTemplate')"), 'tools page should not own appeal template generation logic')
assert(!toolsScript.includes('selectTemplatePlatform'), 'tools page should not show inline platform selection form')
assert(!toolsScript.includes('bindAppealInput'), 'tools page should not bind appeal template form fields inline')
assert(!toolsScript.includes('generateAppealTemplate'), 'tools page should not generate templates inline')
assert(!toolsScript.includes('copyGeneratedTemplate'), 'tools page should not copy generated templates inline')
assert(!toolsScript.includes('请先补全'), 'tools page should not validate template form inline')
assert(!toolsScript.includes('产品链接'), 'tools page script should not include product link wording')

assert(toolsTemplate.includes('bindtap="openTemplateGenerator"'), 'tools page platform rows should open the generator page')
assert(!toolsTemplate.includes('wx:for="{{appealFields}}"'), 'tools page should not render template form fields inline')
assert(!toolsTemplate.includes('template-form-card'), 'tools page should not render a completion form inline')
assert(!toolsTemplate.includes('generated-template-card'), 'tools page should not render generated template inline')
assert(!toolsTemplate.includes('复制模板'), 'tools page should not provide copy action inline')
assert(!toolsTemplate.includes('产品链接'), 'tools page template should not ask for product links')

assert(appConfig.pages.includes('pages/appeal-template/appeal-template'), 'app should register appeal template generator page')

const generatorTemplate = read('pages/appeal-template/appeal-template.wxml')
const generatorScript = read('pages/appeal-template/appeal-template.js')
const appealTemplateService = read('services/appealTemplate.js')

assert(generatorScript.includes("require('../../services/appealTemplate')"), 'generator page should use the appeal template service')
assert(generatorScript.includes('bindAppealInput'), 'generator page should bind appeal form fields')
assert(generatorScript.includes('generateAppealTemplate'), 'generator page should generate templates')
assert(generatorScript.includes('copyGeneratedTemplate'), 'generator page should copy generated templates')
assert(generatorScript.includes('请先补全'), 'generator page should require complete user information')
assert(generatorTemplate.includes('wx:for="{{appealFields}}"'), 'generator page should render every required field')
assert(generatorTemplate.includes('英文专业申诉模板'), 'generator page should present the result as an English professional appeal template')
assert(generatorTemplate.includes('3项关键信息'), 'generator page should tell users only three key fields are required')
assert(generatorTemplate.includes('generated-template-card'), 'generator page should show generated template result')
assert(generatorTemplate.includes('letter-preview'), 'generator page should render the result as a styled letter preview')
assert(generatorTemplate.includes('wx:for="{{generatedTemplateBlocks}}"'), 'generator page should render every generated template block')
assert(generatorTemplate.includes('letter-paragraph'), 'generator page should render template text as readable paragraphs')
assert(generatorTemplate.includes('复制模板'), 'generator page should provide a copy action')
assert(generatorScript.includes('formatAppealTemplateBlocks'), 'generator page should format generated templates into renderable blocks')
assert(generatorScript.includes('generatedTemplateBlocks'), 'generator page should keep renderable blocks in state')
assert(!generatorTemplate.includes('generated-template-area'), 'generator page should not use a fixed-height result textarea')
assert(!generatorTemplate.includes('投诉编号'), 'generator page should not ask for notice numbers')
assert(!generatorTemplate.includes('店铺名称'), 'generator page should not ask for shop names')
assert(!generatorTemplate.includes('联系方式'), 'generator page should not ask for contact information')
assert(appealTemplateService.includes('caseSummary'), 'appeal template service should use the compact case summary field')
assert(appealTemplateService.includes('actionTaken'), 'appeal template service should use the compact action taken field')
assert(appealTemplateService.includes('evidenceReady'), 'appeal template service should use the compact evidence field')
assert(!appealTemplateService.includes('noticeNo'), 'appeal template service should not keep old notice number fields')
assert(!appealTemplateService.includes('shopName'), 'appeal template service should not keep old shop name fields')
assert(!appealTemplateService.includes('contact'), 'appeal template service should not keep old contact fields')
assert(!generatorTemplate.includes('产品链接'), 'generator page should not ask for product links')
assert(!generatorScript.includes('产品链接'), 'generator page script should not include product link wording')
