const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..')

function read(file) {
  return fs.readFileSync(path.join(root, file), 'utf8')
}

const toolsTemplate = read('pages/tools/tools.wxml')
const toolsScript = read('pages/tools/tools.js')
const toolsStyles = read('pages/tools/tools.wxss')
const mockData = require('../data/mock')
const appConfig = require('../app.json')

assert(!toolsTemplate.includes('知识产权服务'), 'tools page should not show an IP service module')
assert(!toolsTemplate.includes('services'), 'tools page should not render the removed service list')
assert(!toolsTemplate.includes('跟卖'), 'tools page should not mention follow-sell monitoring after removal')
assert(!toolsScript.includes('services:'), 'tools page data should not keep removed service pills')
assert(!toolsStyles.includes('.service-card'), 'tools page should not keep removed service card styles')
assert(!toolsStyles.includes('.service-pill'), 'tools page should not keep removed service pill styles')

assert(!toolsTemplate.includes('工具入口'), 'tools page should remove the tool entry section title')
assert(!toolsTemplate.includes('tools-grid'), 'tools page should remove the tool entry grid')
assert(!toolsTemplate.includes('tool-card'), 'tools page should remove tool entry cards')
assert(!toolsTemplate.includes('tool-icon'), 'tools page should remove tool entry icons')
assert(!toolsScript.includes('toolCards'), 'tools page script should not import tool entry data')
assert(!toolsScript.includes('tools:'), 'tools page data should not expose tool entry cards')
assert(!toolsScript.includes('openTool'), 'tools page should remove the removed entry tap handler')
assert(!toolsStyles.includes('.tools-grid'), 'tools page should remove tool grid styles')
assert(!toolsStyles.includes('.tool-card'), 'tools page should remove tool card styles')
assert(!toolsStyles.includes('.tool-icon'), 'tools page should remove tool icon styles')
assert(!Object.prototype.hasOwnProperty.call(mockData, 'toolCards'), 'shared mock data should not export removed tool entry cards')

assert(toolsScript.includes('openTemplateGenerator'), 'tools page should navigate to the template generator page')
assert(toolsScript.includes('/pages/appeal-template/appeal-template?platform='), 'tools page should pass selected platform to generator page')
assert(toolsScript.includes('wx.navigateTo'), 'tools page should use page navigation for template generation')
assert(toolsTemplate.includes('港港跨境 AI 助手'), 'tools page should rename the appeal assistant to the GGKJ AI assistant')
assert(toolsTemplate.includes('开始聊天'), 'tools page should make the assistant button start a chat')
assert(toolsTemplate.includes('bindtap="openAiAssistant"'), 'tools page assistant card should open the AI chat page')
assert(toolsScript.includes('openAiAssistant'), 'tools page should expose an AI assistant navigation handler')
assert(toolsScript.includes('/pages/ai-chat/ai-chat'), 'tools page should navigate to the AI chat page')
assert(!toolsTemplate.includes('英文申诉信助手'), 'tools page should not keep the old appeal assistant title')
assert(!toolsTemplate.includes('开始撰写'), 'tools page should not keep the old writing CTA')
assert(!toolsScript.includes('申诉信AI接口待接入'), 'tools page should not show the old placeholder toast')
assert(!toolsScript.includes("require('../../services/appealTemplate')"), 'tools page should not own appeal template generation logic')
assert(!toolsScript.includes('selectTemplatePlatform'), 'tools page should not show inline platform selection form')
assert(!toolsScript.includes('bindAppealInput'), 'tools page should not bind appeal template form fields inline')
assert(!toolsScript.includes('generateAppealTemplate'), 'tools page should not generate templates inline')
assert(!toolsScript.includes('copyGeneratedTemplate'), 'tools page should not copy generated templates inline')
assert(!toolsScript.includes('请先补全'), 'tools page should not validate template form inline')
assert(!toolsScript.includes('产品链接'), 'tools page script should not include product link wording')

assert(toolsTemplate.includes('bindtap="openTemplateGenerator"'), 'tools page platform rows should open the generator page')
assert(!toolsTemplate.includes('wx:for="{{appealFields}}"'), 'tools page should not render template form fields inline')
assert(!toolsTemplate.includes('template-form-card'), 'tools page should not render a completion form inline')
assert(!toolsTemplate.includes('generated-template-card'), 'tools page should not render generated template inline')
assert(!toolsTemplate.includes('复制模板'), 'tools page should not provide copy action inline')
assert(!toolsTemplate.includes('产品链接'), 'tools page template should not ask for product links')

assert(appConfig.pages.includes('pages/appeal-template/appeal-template'), 'app should register appeal template generator page')
assert(appConfig.pages.includes('pages/ai-chat/ai-chat'), 'app should register the AI chat page')

const chatTemplate = read('pages/ai-chat/ai-chat.wxml')
const chatScript = read('pages/ai-chat/ai-chat.js')
const chatStyles = read('pages/ai-chat/ai-chat.wxss')

assert(chatTemplate.includes('scroll-view'), 'AI chat page should render messages in a scrollable conversation')
assert(chatTemplate.includes('message-user'), 'AI chat page should render user messages on the right')
assert(chatTemplate.includes('message-assistant'), 'AI chat page should render assistant messages on the left')
assert(chatTemplate.includes('bindtap="openAttachmentMenu"'), 'AI chat page should use one plus button for attachments')
assert(!chatTemplate.includes('bindtap="chooseImage"'), 'AI chat page should not show a separate image button in the composer')
assert(!chatTemplate.includes('bindtap="chooseFile"'), 'AI chat page should not show a separate file button in the composer')
assert(chatTemplate.includes('sendMessage'), 'AI chat page should send chat messages')
assert(chatScript.includes("require('../../services/chatAssistant')"), 'AI chat page should call the chat assistant service')
assert(chatScript.includes("require('../../services/chatAttachments')"), 'AI chat page should use the chat attachment service')
assert(chatScript.includes('openAttachmentMenu'), 'AI chat page should expose a plus-menu handler')
assert(chatScript.includes('showActionSheet'), 'AI chat page should open a native attachment action sheet')
assert(chatScript.includes('chooseMedia'), 'AI chat page should use media picking when available')
assert(chatScript.includes('chooseMessageFile'), 'AI chat page should support file picking')
assert(chatStyles.includes('.composer-input-wrap'), 'AI chat styles should give the text input the main composer width')
assert(chatStyles.includes('.composer-plus'), 'AI chat styles should include a plus attachment button')
assert(chatStyles.includes('flex: 1 1 auto'), 'AI chat input should take the remaining composer width')
assert(chatStyles.includes('flex: 0 0 72rpx'), 'AI chat action buttons should be fixed square controls')
assert(chatStyles.includes('min-width: 0'), 'AI chat input wrapper should allow the input to expand without wrapping placeholder text')
assert(!chatStyles.includes('width: 104rpx'), 'AI chat send button should not keep the old wide rectangle width')
assert(!chatStyles.includes('.composer-tool'), 'AI chat styles should remove separate image/file tool buttons')
assert(chatStyles.includes('.message-user'), 'AI chat styles should include right-aligned user bubbles')
assert(chatStyles.includes('.message-assistant'), 'AI chat styles should include left-aligned assistant bubbles')

const generatorTemplate = read('pages/appeal-template/appeal-template.wxml')
const generatorScript = read('pages/appeal-template/appeal-template.js')
const appealTemplateService = read('services/appealTemplate.js')

assert(generatorScript.includes("require('../../services/appealTemplate')"), 'generator page should use the appeal template service')
assert(generatorScript.includes('bindAppealInput'), 'generator page should bind appeal form fields')
assert(generatorScript.includes('generateAppealTemplate'), 'generator page should generate templates')
assert(generatorScript.includes('copyGeneratedTemplate'), 'generator page should copy generated templates')
assert(generatorScript.includes('请先补全'), 'generator page should require complete user information')
assert(generatorTemplate.includes('wx:for="{{appealFields}}"'), 'generator page should render every required field')
assert(generatorTemplate.includes('英文专业申诉模板'), 'generator page should present the result as an English professional appeal template')
assert(generatorTemplate.includes('3项关键信息'), 'generator page should tell users only three key fields are required')
assert(generatorTemplate.includes('generated-template-card'), 'generator page should show generated template result')
assert(generatorTemplate.includes('letter-preview'), 'generator page should render the result as a styled letter preview')
assert(generatorTemplate.includes('wx:for="{{generatedTemplateBlocks}}"'), 'generator page should render every generated template block')
assert(generatorTemplate.includes('letter-paragraph'), 'generator page should render template text as readable paragraphs')
assert(generatorTemplate.includes('复制模板'), 'generator page should provide a copy action')
assert(generatorScript.includes('formatAppealTemplateBlocks'), 'generator page should format generated templates into renderable blocks')
assert(generatorScript.includes('generatedTemplateBlocks'), 'generator page should keep renderable blocks in state')
assert(!generatorTemplate.includes('generated-template-area'), 'generator page should not use a fixed-height result textarea')
assert(!generatorTemplate.includes('投诉编号'), 'generator page should not ask for notice numbers')
assert(!generatorTemplate.includes('店铺名称'), 'generator page should not ask for shop names')
assert(!generatorTemplate.includes('联系方式'), 'generator page should not ask for contact information')
assert(appealTemplateService.includes('caseSummary'), 'appeal template service should use the compact case summary field')
assert(appealTemplateService.includes('actionTaken'), 'appeal template service should use the compact action taken field')
assert(appealTemplateService.includes('evidenceReady'), 'appeal template service should use the compact evidence field')
assert(!appealTemplateService.includes('noticeNo'), 'appeal template service should not keep old notice number fields')
assert(!appealTemplateService.includes('shopName'), 'appeal template service should not keep old shop name fields')
assert(!appealTemplateService.includes('contact'), 'appeal template service should not keep old contact fields')
assert(!generatorTemplate.includes('产品链接'), 'generator page should not ask for product links')
assert(!generatorScript.includes('产品链接'), 'generator page script should not include product link wording')
